sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Y1UGT4oSAU8qRqOfAIVg7VeFNERjlN8rgPuY/2HqcN5k9LqHNob4+w+xSPV8bFvU81IuqLPBXKWbZYtLX4pp33OsD18FVHPLFOuE/OWX4CThZlauG7F8SPXtlHrx7vupxJe0wKWMJIEop19eRVzNmoRTUHPdX80+a/0APAEtAQRdFJzhe7R+GXSX6i1aeRbSA2WvT69UU2CERrKolhmQOgXQOmM0UXfYu+GGDy3o7Xv9Dmo7wfby0u72fQ78cB9iK9FX4eyP6jtGhEShKkbB9mtn2MiC2ZKHPCpD6qEBrLOlhkbsFAOYygNNp9P925B9y5pj9//rbivLrd62kdB+kIkSez6VVMCxYpvMD+0fh8+uFyfvFSk5mDWPLonskRtTtBqYgITuuu72hBuA2sluSMPBL6G0GaDbfsGn9xRd4aOyH2iY+6k1AVlyBwx7FUbUwqwUWq5BaY+ZIi9d0yYIJv8wmgUQYT9KzfzMf+jBmDRpyRwn6PqEgrlJYPJrdTPuVW6n94PPHrmnImnCA1c9BpOKksLfieV5kZZL4lHiuBzvxe340tMwUkllZY+dZUsHkOUCfiP4xepav0F4nXKZ1HCRbv15yqtonfEoKAfR78QSFaQ4nD2rHIBHkO7q5ZbB+aZBG+rlBEtS/rT4bz2XkQOll4uho6tLLDGAhZRJ22w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Sermons-on-the-Card-and-Other-Discourses_2458
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy